name: OrangePi3 Kernel ARM64 latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build linux master
    runs-on: ubuntu-20.04

    steps:
    - name: cleanup ubuntu server
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get build-dep -y linux
          sudo -E apt-get install -y crossbuild-essential-arm64
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
    - name: checkout
      uses: actions/checkout@v3
      with:
          ref: master

    - name: make defconfig
      run: make CROSS_COMPILE=aarch64-none-linux-gnu- ARCH=arm64 defconfig

    - name: make all
      run: make CROSS_COMPILE=aarch64-none-linux-gnu- ARCH=arm64 all
